export const INITIAL_SHOP_ITEMS = [
  // Skins
  {
    id: 'skin_ninja',
    name: 'Foca Ninja',
    price: 80,
    description: 'Um traje furtivo para focar nas sombras e fatiar a procrastinação.',
    iconName: 'Shield',
    type: 'skin',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_astronauta',
    name: 'Foca Astronauta',
    price: 150,
    description: 'Roupa espacial de ponta para foco de outro mundo!',
    iconName: 'Rocket',
    type: 'skin',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_mago',
    name: 'Foca Mago',
    price: 220,
    description: 'Convoque feitiços de altíssima produtividade com este manto arcano.',
    iconName: 'Sparkles',
    type: 'skin',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_oculos',
    name: 'Juliete estilosa',
    price: 60,
    description: 'Um acessório chave para deixar sua foca com o puro estilo das ruas.',
    iconName: 'Palette',
    type: 'skin',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_dev',
    name: 'Foca Desenvolvedora',
    price: 150,
    description: 'Equipada com óculos de nerd e um notebook. Para sprints intensos de código.',
    iconName: 'Zap',
    type: 'skin',
    purchased: false,
    equipped: false,
  },
  // Consumíveis (comidas e bebidas)
  {
    id: 'food_pao_queijo',
    name: 'Pão de queijo',
    price: 10,
    description: 'Recupera +15 de Energia. Um clássico quentinho.',
    iconName: 'Shield',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_pizza',
    name: 'Pizza',
    price: 25,
    description: 'Recupera +35 de Energia. Deliciosa fatia cheia de queijo.',
    iconName: 'Shield',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_hamburguer',
    name: 'Hambúrguer Rei',
    price: 35,
    description: 'Recupera +50 de Energia. Refeição dos campeões.',
    iconName: 'Shield',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_churrasco',
    name: 'Churrasquinho',
    price: 30,
    description: 'Recupera +45 de Energia. Feito na brasa.',
    iconName: 'Shield',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_salada',
    name: 'Salada',
    price: 15,
    description: 'Recupera +20 de Energia. Prato de verduras focado na saúde.',
    iconName: 'Shield',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_cafe',
    name: 'Cafezinho',
    price: 15,
    description: 'Recupera +20 de Energia. Uma dose dupla de cafeína pura.',
    iconName: 'Rocket',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_energetico_red',
    name: 'Energético Touro Vermelho',
    price: 25,
    description: 'Recupera +35 de Energia. Te dá asas virtuais.',
    iconName: 'Rocket',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_energetico_monster',
    name: 'Energético Monstruoso',
    price: 35,
    description: 'Recupera +50 de Energia. Dose letal de foco e produtividade.',
    iconName: 'Rocket',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_refri_cola',
    name: 'Refrigerante Cola Misterioso',
    price: 20,
    description: 'Recupera +30 de Energia. Açúcar rápido para a mente.',
    iconName: 'Rocket',
    type: 'food',
    purchased: false,
    quantity: 0,
  },
  // Itens especiais
  {
    id: 'mystery_box',
    name: 'Caixa Misteriosa',
    price: 30,
    description: 'Pode vir comida, bebida ou com 10% de chance, a sagrada Poção de Reviver!',
    iconName: 'Sparkles',
    type: 'mystery_box',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'potion_revive',
    name: 'Poção de Reviver',
    price: 300,
    description: 'Ressuscita uma Foca abatida imediatamente. (Limite de 2 por semana)',
    iconName: 'Bell',
    type: 'potion',
    purchased: false,
    quantity: 0,
    weeklyPurchasedCount: 0,
  },
];


export const INITIAL_TASKS = [];

// Estatísticas INICIAIS – ZERADAS: sem dinheiro, sem streak, sem minutos
export const INITIAL_STATS = {
  coins: 0,
  focusMinutesToday: 0,
  totalDaysActive: 0,
  currentStreak: 0,
  longestStreak: 0,
  weeklyFocus: [
    { day: 'Seg', minutes: 0 },
    { day: 'Ter', minutes: 0 },
    { day: 'Qua', minutes: 0 },
    { day: 'Qui', minutes: 0 },
    { day: 'Sex', minutes: 0 },
    { day: 'Sáb', minutes: 0 },
    { day: 'Dom', minutes: 0 },
  ],
  monthlyFocus: Array.from({ length: 30 }, () => ({ date: '', minutes: 0 })),
  yearlyFocus: [
    { month: 'Jan', minutes: 0 },
    { month: 'Fev', minutes: 0 },
    { month: 'Mar', minutes: 0 },
    { month: 'Abr', minutes: 0 },
    { month: 'Mai', minutes: 0 },
    { month: 'Jun', minutes: 0 },
    { month: 'Jul', minutes: 0 },
    { month: 'Ago', minutes: 0 },
    { month: 'Set', minutes: 0 },
    { month: 'Out', minutes: 0 },
    { month: 'Nov', minutes: 0 },
    { month: 'Dez', minutes: 0 },
  ],
};