

export const INITIAL_SHOP_ITEMS = [
  {
    id: 'skin_ninja',
    name: 'Foca Ninja',
    price: 80,
    description: 'Um traje furtivo para focar nas sombras e fatiar a procrastinação.',
    iconName: 'Shield',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_astronauta',
    name: 'Foca Astronauta',
    price: 150,
    description: 'Roupa espacial de ponta para foco de outro mundo!',
    iconName: 'Rocket',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_mago',
    name: 'Foca Mago',
    price: 220,
    description: 'Convoque feitiços de altíssima produtividade com este manto arcano.',
    iconName: 'Sparkles',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_oculos',
    name: 'Juliete estilosa',
    price: 60,
    description: 'Um acessório chave para deixar sua foca com o puro estilo das ruas.',
    iconName: 'Palette',
    purchased: false,
    equipped: false,
  },
  // Consumíveis p/ Nutrição ou Engajamentos energéticos! 
  {
    id: 'food_pao_queijo',
    name: 'Pão de queijo',
    price: 10,
    description: 'Recupera +15 de Energia. Um clássico quentinho.',
    iconName: 'Shield',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_pizza',
    name: 'Pizza',
    price: 25,
    description: 'Recupera +35 de Energia. Deliciosa fatia cheia de queijo.',
    iconName: 'Shield',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_hamburguer',
    name: 'Hambúrguer Rei',
    price: 35,
    description: 'Recupera +50 de Energia. Refeição dos campeões.',
    iconName: 'Shield',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_churrasco',
    name: 'Churrasquinho',
    price: 30,
    description: 'Recupera +45 de Energia. Feito na brasa.',
    iconName: 'Shield',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'food_salada',
    name: 'Salada',
    price: 15,
    description: 'Recupera +20 de Energia. Prato de verduras focado na saúde.',
    iconName: 'Shield',
    purchased: false,
    quantity: 0,
  },
  // Consumíveis focados  em Energia Rápida ou Foco Imediato p/ Mascote!
  {
    id: 'drink_cafe',
    name: 'Cafezinho',
    price: 15,
    description: 'Recupera +20 de Energia. Uma dose dupla de cafeína pura.',
    iconName: 'Rocket',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_energetico_red',
    name: 'Energético Touro Vermelho',
    price: 25,
    description: 'Recupera +35 de Energia. Te dá asas virtuais.',
    iconName: 'Rocket',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_energetico_monster',
    name: 'Energético Monstruoso',
    price: 35,
    description: 'Recupera +50 de Energia. Dose letal de foco e produtividade.',
    iconName: 'Rocket',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'drink_refri_cola',
    name: 'Refrigerante Cola Misterioso',
    price: 20,
    description: 'Recupera +30 de Energia. Açúcar rápido para a mente.',
    iconName: 'Rocket',
    purchased: false,
    quantity: 0,
  },
  // Itens mystery_box e potion_revive
  {
    id: 'mystery_box',
    name: 'Caixa Misteriosa',
    price: 30,
    description: 'Pode vir comida, bebida ou com 10% de chance, a sagrada Poção de Reviver!',
    iconName: 'Sparkles',
    purchased: false,
    quantity: 0,
  },
  {
    id: 'potion_revive',
    name: 'Poção de Reviver',
    price: 300,
    description: 'Ressuscita uma Foca abatida imediatamente. (Estoque: Limite de 2 por semana)',
    iconName: 'Bell',
    purchased: false,
    quantity: 0,
    weeklyPurchasedCount: 0,
  },
  {
    id: 'skin_ninja',
    name: 'Foca das Sombras',
    price: 80,
    description: 'Transforma sua foca em um Ninja Silencioso. Mais foco, menos distrações.',
    iconName: 'Shield',
    purchased: false,
    equipped: false,
  },
  {
    id: 'skin_dev',
    name: 'Foca Desenvolvedora',
    price: 150,
    description: 'Equipada com óculos de nerd e um notebook. Para sprints intensos de código.',
    iconName: 'Zap',
    purchased: false,
    equipped: false,
  },
];

export const INITIAL_TASKS = [
  {
    id: 'task-1',
    title: 'Estudar conceitos de UX/UI para Bento Grid',
    description: 'Ler sobre layouts modernos e como organizar informações de forma visualmente harmônica e modular.',
    estimatedPomodoros: 2,
    completedPomodoros: 1,
    completed: false,
    createdAt: new Date().toISOString(),
    priority: 'importante',
  },
  {
    id: 'task-2',
    title: 'Codificar componente Pomodoro interativo',
    description: 'Terminar lógica do cronômetro, toque de alarmes e transições fluidas com Framer Motion.',
    estimatedPomodoros: 3,
    completedPomodoros: 0,
    completed: false,
    createdAt: new Date().toISOString(),
    priority: 'urgente',
  },
  {
    id: 'task-3',
    title: 'Revisar fluxo de gamificação e barra de energia',
    description: 'Ajustar decaimento de energia por tarefa completada e ganho por ciclo.',
    estimatedPomodoros: 1,
    completedPomodoros: 1,
    completed: true,
    createdAt: new Date().toISOString(),
    priority: 'normal',
  },
];

export const INITIAL_STATS = {
  coins: 60,
  focusMinutesToday: 45,
  totalDaysActive: 4,
  currentStreak: 3,
  longestStreak: 5,
  weeklyFocus: [
    { day: 'Seg', minutes: 25 },
    { day: 'Ter', minutes: 50 },
    { day: 'Qua', minutes: 0 },
    { day: 'Qui', minutes: 75 },
    { day: 'Sex', minutes: 45 },
    { day: 'Sáb', minutes: 25 },
    { day: 'Dom', minutes: 0 },
  ],
  monthlyFocus: Array.from({ length: 30 }, (_, i) => ({
    date: `${i + 1}`,
    minutes: Math.max(0, Math.round(i % 4 === 0 ? 0 : 30 + Math.sin(i) * 25)),
  })),
  yearlyFocus: [
    { month: 'Jan', minutes: 450 },
    { month: 'Fev', minutes: 600 },
    { month: 'Mar', minutes: 800 },
    { month: 'Abr', minutes: 720 },
    { month: 'Mai', minutes: 950 },
    { month: 'Jun', minutes: 1200 },
    { month: 'Jul', minutes: 0 },
    { month: 'Ago', minutes: 0 },
    { month: 'Set', minutes: 0 },
    { month: 'Out', minutes: 0 },
    { month: 'Nov', minutes: 0 },
    { month: 'Dez', minutes: 0 },
  ],
};
